// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGp4KQtPz-b5yT4DSwsBeil1D3LlOKB2o',
    appId: '1:840774462334:web:06604be768b4b4f0ff212f',
    messagingSenderId: '840774462334',
    projectId: 'opinio-49707',
    authDomain: 'opinio-49707.firebaseapp.com',
    storageBucket: 'opinio-49707.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlJb5DUSLKBa1ZE7vgWdwzDYS0WzFnrzQ',
    appId: '1:840774462334:ios:aa2332ef988f4ccfff212f',
    messagingSenderId: '840774462334',
    projectId: 'opinio-49707',
    storageBucket: 'opinio-49707.appspot.com',
    iosBundleId: 'com.example.opinio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlJb5DUSLKBa1ZE7vgWdwzDYS0WzFnrzQ',
    appId: '1:840774462334:ios:aa2332ef988f4ccfff212f',
    messagingSenderId: '840774462334',
    projectId: 'opinio-49707',
    storageBucket: 'opinio-49707.appspot.com',
    iosBundleId: 'com.example.opinio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGp4KQtPz-b5yT4DSwsBeil1D3LlOKB2o',
    appId: '1:840774462334:web:c1f9e6eb26224afeff212f',
    messagingSenderId: '840774462334',
    projectId: 'opinio-49707',
    authDomain: 'opinio-49707.firebaseapp.com',
    storageBucket: 'opinio-49707.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJHqXGYQheQv9C_OFA2rGjKWtRinK2Mik',
    appId: '1:840774462334:android:e2745fc3df62510eff212f',
    messagingSenderId: '840774462334',
    projectId: 'opinio-49707',
    storageBucket: 'opinio-49707.appspot.com',
  );

}